### ISSUE TITLE
[PE-D] addTask allows users to indicate elderly names that do not exist in NurseyBook

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-2/tp#156]
The user is able to add an invalid elderly name(i.e A name that has not been added to NurseryBook) to a task, as shown in the screenshot below. 
Steps to reproduce:
1. addTask desc/check insulin date/2021-10-29 time/23:00 en/Notaneldery

![Screenshot 2021-10-29 at 4.47.55 PM.png](https://raw.githubusercontent.com/amzhy/ped/main/files/134caae7-e11d-4824-af2e-d38e6f3c2d73.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: amzhy/ped#4

**Comment by nicole-luo-exe** [comment]
Similar to #198
