### ISSUE TITLE
[PE-D] Final Comments

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-2/tp#165]
To be honest your app looks really damn sick! I had a hard time finding bugs, but there are still some cases that I've identified. Hope I've been of help to you guys and all the best for v1.4

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: rushilramesh/ped#13

**Comment by nicole-luo-exe** [comment]
Thank you! 😸
