### ISSUE TITLE
[PE-D] Overly long text will cause long horizontal scrolling and weird empty spaces

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-2/tp#166]
Adding a very long name for `addElderly` or other long inputs for other parameters will cause the UI to have weird spacings

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: alissayarmantho/ped#10

**Comment by nicole-luo-exe** [comment]
Not that big an issue in terms of functionality.
