### ISSUE TITLE
[PE-D] Recurring tasks that has passed the task time (overdue) just disappear from the list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-2/tp#170]
When making a recurring weekly task and it has passed the timing of the task, it will automatically change to next week's date and the previous task that is still not marked as done has disappeared from the task list. 

Perhaps a user might want to complete an overdue recurring task instead of deleting it from the task list.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: alissayarmantho/ped#12

**Comment by xiongjya** [comment]
Considered as a feature flaw, will not be fixing this in milestone v1.4.
