### ISSUE TITLE
[PE-D] Small formatting inconsistency in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-2/tp#183]
Would be nice for column width to be the same for all command columns:
![ug formatting.png](https://raw.githubusercontent.com/weiquu/ped/main/files/6575d892-6704-423c-94e5-89d023e6f20e.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: weiquu/ped#15

**Comment by xiongjya** [comment]
Minor issue that might not be possible to handle on markdown (as markdown has its limitations). Even if possible, will not be completing for v1.4. The suggestion will however, be kept in consideration.
