### ISSUE TITLE
[PE-D] Dates are not updated automatically for recurring tasks as stated in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-2/tp#189]
The dates are not updated automatically for the tasks as expected, after a few mins had elapsed since the time of the task. In the example shown in the screenshot, the date is expected to be updated to 2021-11-26 but the date shown remains as 2021-10-29. Similar outputs were observed for recurring daily and weekly tasks. 

![image.png](https://raw.githubusercontent.com/amzhy/ped/main/files/fa6d8ccd-2e7d-4eb9-94a6-76dec7f11797.png)

The app has to be restarted in order for the date to be updated correctly to 2021-11-26.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: amzhy/ped#11

**Comment by Superbestron** [comment]
Will update UG to make it clearer
