### ISSUE TITLE
[PE-D] Date is not updated when task recurrence is changed from monthly to weekly

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-2/tp#194]
If the recurrence of a task is changed from monthly to weekly, only the text indicating the type is changed, the date remains unchanged, even though the user would expect the date to be changed to a much earlier date. For example:

Date: 2021-10-29
1. addTask desc/give medicine date/2021-10-29 time/12:30 recur/monthly

Date: 2021-10-31 (User realises that the task should be weekly and not a monthly task)
2. editTask 1 recur/week

The date should be changed to 2021-11-05 which is a week from the initial date of the task, but it remains unchanged at 2021-10-29 (another bug which does not update date automatically to a month ahead).

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: amzhy/ped#16

**Comment by Superbestron** [comment]
Need to be clearer in UG
