### ISSUE TITLE
[PE-D] Behaviour when changing task recurrence from daily to weekly is unclear

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-2/tp#195]
If the user changes the recurrence type from daily to weekly, would the user expect the updated date to be a week from the day that he edits the task or a week from the initial date of the task? This is unclear as it is not specified in the user guide. For example:

Date: 2021-10-29

1. addTask desc/give medicine date/2021-10-29 time/12:30 recur/daily

Date: 2021-10-31 (User realises that the task should be weekly and not a daily task)

2. editTask 1 recur/week

Would the date of the task be updated to 2021-11-07 or 2021-11-05?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: amzhy/ped#17

**Comment by nicole-luo-exe** [comment]
Be clearer in user guide
