### ISSUE TITLE
[PE-D] Terms used in UG might not be clear enough for first-time users

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-2/tp#196]
![image.png](https://raw.githubusercontent.com/amzhy/ped/main/files/15f6620f-de77-44ff-8d0e-972744db8129.png)

'NOK' abbreviation was not explained clearly in the glossary or anywhere else in the user guide, as a first-time user I had to guess or Google what it meant before I could use the commands. Perhaps it could be defined clearly in the beginning before using the abbreviation for the rest of the user guide. 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: amzhy/ped#18

**Comment by xiongjya** [comment]
Refer to #219 if shortly mentioning next-of-kin will be sufficient to users. If not, feel free to include more!
